import { BALANCE_COLUMNS } from '../dictionary';
import { getBalanceToIncrement } from '@db/cli/utils.js';
/**
 * This class represents a row from the COINBASE_BALANCE_LEDGER table
 */
export default class Balance {
  constructor(row) {
    for (const [key, value] of Object.entries(BALANCE_COLUMNS)) {
      if (value === BALANCE_COLUMNS.ID) {
        /**
         * Do not require the ID
         * this is generated by the database
         * removing this check means we can synthesize new Balance instances
         */
        continue;
      }

      if (!Object.hasOwn(row, value)) {
        console.dir(row);
        throw new Error(`Balance column is missing ${key}: ${value}`);
      }
    }
    this.row = row;
  }
  /**
   * @returns {string} - CSV string
   */
  get id() {
    return this.row[BALANCE_COLUMNS.ID];
  }
  /**
   * @returns {Date} - Date returned from the DB
   */
  get timestamp() {
    return this.row[BALANCE_COLUMNS.TIMESTAMP];
  }
  /**
   * @returns {string} - CSV string
   */
  get asset() {
    return this.row[BALANCE_COLUMNS.ASSET];
  }
  /**
   * @returns {string}
   */
  get balance() {
    return this.row[BALANCE_COLUMNS.BALANCE];
  }
  /**
   * @returns {string} - CSV string
   */
  get tx_id() {
    return this.row[BALANCE_COLUMNS.TX_ID];
  }

  /**
   * @returns {string} - CSV string
   */
  get notes() {
    return this.row[BALANCE_COLUMNS.NOTES];
  }

  /**
   * @param {boolean} raw - return the raw value from the DB
   * @param {null|string} current - optionally decorate with the current price
   * @returns {Promise<{timestamp: Date, asset: string, notes: string}>}
   */
  async toTableRow(raw = false, current = null) {
    const row = {
      // id: this.id,//Necessary?
      tx_id: this.tx_id,
      timestamp: this.timestamp,
      asset: this.asset,
      notes: this.notes,
    };

    if (raw) {
      row['balance'] = this.balance;
    } else {
      row['balance'] = await getBalanceToIncrement(this.asset, this.balance, false);
    }

    if (current) {
      row['current'] = current;
    }

    return row;
  }

  /**
   * @returns {(Date|string)[]}
   */
  toSqlValues() {
    return [this.timestamp, this.asset, this.balance, this.tx_id, this.notes];
  }
}
